name: CI

on:
  push:
    branches:
      - feature/v1

jobs:
  build:
    runs-on: ubuntu-latest
    container: nikolaik/python-nodejs:python3.8-nodejs12
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Dev stage
      env:
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        SITE_TARGET_NAME_DEV: ${{ secrets.SITE_TARGET_NAME_DEV }}
      run: | 
        ./.ci/scripts/ci-dev.sh $PWD